services:
  postgres:
    image: postgres:16
    container_name: deb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: deb
      POSTGRES_USER: deb
      POSTGRES_PASSWORD: deb
    ports:
      - "5432:5432"
    volumes:
      - deb-postgres-data:/var/lib/postgresql/data

volumes:
  deb-postgres-data:
