import { readFileSync } from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";

export function registerWorkerGuideArchitectureAssertions({ test, workerRoot }) {
  test("worker Vision guide route keeps paid OpenAI screen guidance outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const routesSource = readFileSync(path.join(workerRoot, "src", "workerRoutes.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");

    assert.match(routesSource, /from "\.\/visionGuideRoutes"/);
    assert.match(routesSource, /handleVisionGuide\(request, env\)/);
    assert.match(visionGuideRoutesSource, /export async function handleVisionGuide/);
    assert.match(visionGuideRoutesSource, /requirePaidUser\(request, env\)/);
    assert.match(visionGuideRoutesSource, /readBoundedRequestText\(request, maxPayloadBytes/);
    assert.match(visionGuideRoutesSource, /parseJSONText<SpiderVisionGuideRequest>/);
    assert.match(visionGuideRoutesSource, /validateVisionGuideRequest\(body, GUIDE_REQUEST_VALIDATION_POLICY\)/);
    assert.match(visionGuideRoutesSource, /requireOpenAISecret\(env\)/);
    assert.match(visionGuideRoutesSource, /configuredOpenAIModel\(env\.OPENAI_VISION_MODEL/);
    assert.match(visionGuideRoutesSource, /consumeRequestRateLimits\(request, env, "vision"/);
    assert.match(visionGuideRoutesSource, /consumeQuota\(env, user\.id, "vision"/);
    assert.match(visionGuideRoutesSource, /recordAuditEvent\(env, user\.id, "vision_guide_requested"\)/);
    assert.match(visionGuideRoutesSource, /requestOpenAIGuideOutputText\(\{/);
    assert.match(visionGuideRoutesSource, /buildOpenAIGuideRequestPayload\(body, visionModel, user\.emailHash\)/);
    assert.match(visionGuideRoutesSource, /safetyIdentifier: user\.emailHash/);
    assert.match(visionGuideRoutesSource, /guideResponsePayload\(outputText, guideValidationContextForRequest\(body\)\)/);
    assert.doesNotMatch(indexSource, /function handleVisionGuide\(/);
    assert.doesNotMatch(indexSource, /from "\.\/visionGuideRoutes"/);
    assert.doesNotMatch(indexSource, /vision_guide_requested/);
    assert.doesNotMatch(indexSource, /MAX_SCREENSHOT_PAYLOAD_BYTES/);
  });

  test("worker guide contracts stay outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const routesSource = readFileSync(path.join(workerRoot, "src", "workerRoutes.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");
    const guideTypesSource = readFileSync(path.join(workerRoot, "src", "guideTypes.ts"), "utf8");

    assert.match(routesSource, /from "\.\/visionGuideRoutes"/);
    assert.match(visionGuideRoutesSource, /from "\.\/guideTypes"/);
    assert.match(guideTypesSource, /export interface SpiderScreenshot/);
    assert.match(guideTypesSource, /export interface SpiderVisionGuideRequest/);
    assert.match(guideTypesSource, /export interface GuideSemanticGrounding/);
    assert.match(guideTypesSource, /export interface GuideSemanticTarget/);
    assert.match(guideTypesSource, /export interface GuideSceneGraphElement/);
    assert.match(guideTypesSource, /export interface GuidePoint/);
    assert.match(guideTypesSource, /export interface GuidePointAuditorDecision/);
    assert.match(guideTypesSource, /export type GroundingCorroborationSource/);
    assert.match(guideTypesSource, /import type \{ SpiderPlatformRequestContext \}/);
    assert.doesNotMatch(indexSource, /interface SpiderScreenshot/);
    assert.doesNotMatch(indexSource, /interface SpiderVisionGuideRequest/);
    assert.doesNotMatch(indexSource, /interface GuideSemanticGrounding/);
    assert.doesNotMatch(indexSource, /interface GuidePointAuditorDecision/);
    assert.doesNotMatch(indexSource, /type GroundingCorroborationSource/);
    assert.doesNotMatch(routesSource, /interface SpiderVisionGuideRequest/);
    assert.doesNotMatch(routesSource, /interface GuideSemanticGrounding/);
    assert.doesNotMatch(routesSource, /interface GuidePointAuditorDecision/);
  });

  test("worker guide limits stay outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const guideLimitsSource = readFileSync(path.join(workerRoot, "src", "guideLimits.ts"), "utf8");
    const requestValidationSource = readFileSync(path.join(workerRoot, "src", "guideRequestValidation.ts"), "utf8");
    const responseValidationSource = readFileSync(path.join(workerRoot, "src", "guideResponseValidation.ts"), "utf8");
    const responseSchemaSource = readFileSync(path.join(workerRoot, "src", "guideResponseSchema.ts"), "utf8");
    const openAIResponseSource = readFileSync(path.join(workerRoot, "src", "openAIGuideResponse.ts"), "utf8");

    assert.match(guideLimitsSource, /export const MAX_OPENAI_RESPONSE_BYTES = 1_000_000/);
    assert.match(guideLimitsSource, /export const MAX_SINGLE_SCREENSHOT_BASE64_CHARS = 7_500_000/);
    assert.match(guideLimitsSource, /export const MAX_USER_TRANSCRIPT_CHARS = 12_000/);
    assert.match(guideLimitsSource, /export const MAX_GUIDE_OUTPUT_TEXT_CHARS = 200_000/);
    assert.match(guideLimitsSource, /export const MAX_GUIDE_CONTEXT_KIND_CHARS = 64/);
    assert.match(guideLimitsSource, /export const MAX_GUIDE_GROUNDING_TARGETS = 8/);
    assert.match(guideLimitsSource, /export const MAX_AD_MISSION_TEXT_FIELD_CHARS = 8_000/);
    assert.match(guideLimitsSource, /export const MIN_GUIDE_TARGET_REGION_PIXELS = 4/);
    assert.match(guideLimitsSource, /export const ALLOWED_SCREENSHOT_MIME_TYPES = new Set/);
    assert.match(requestValidationSource, /from "\.\/guideLimits"/);
    assert.match(responseValidationSource, /from "\.\/guideLimits"/);
    assert.match(responseSchemaSource, /from "\.\/guideLimits"/);
    assert.match(openAIResponseSource, /from "\.\/guideLimits"/);
    assert.doesNotMatch(indexSource, /from "\.\/guideLimits"/);
    assert.doesNotMatch(indexSource, /const MAX_OPENAI_RESPONSE_BYTES =/);
    assert.doesNotMatch(indexSource, /const MAX_SINGLE_SCREENSHOT_BASE64_CHARS =/);
    assert.doesNotMatch(indexSource, /const MAX_USER_TRANSCRIPT_CHARS =/);
    assert.doesNotMatch(indexSource, /const MAX_GUIDE_OUTPUT_TEXT_CHARS =/);
    assert.doesNotMatch(indexSource, /const MAX_AD_MISSION_TEXT_FIELD_CHARS =/);
    assert.doesNotMatch(indexSource, /const MIN_GUIDE_TARGET_REGION_PIXELS =/);
    assert.doesNotMatch(indexSource, /const ALLOWED_SCREENSHOT_MIME_TYPES =/);
  });

  test("worker guide request validation stays outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");
    const validationSource = readFileSync(path.join(workerRoot, "src", "guideRequestValidation.ts"), "utf8");
    const contractSource = readFileSync(path.join(workerRoot, "src", "guideResponseContract.ts"), "utf8");

    assert.match(visionGuideRoutesSource, /from "\.\/guideRequestValidation"/);
    assert.match(visionGuideRoutesSource, /from "\.\/guideResponseContract"/);
    assert.match(visionGuideRoutesSource, /validateVisionGuideRequest\(body, GUIDE_REQUEST_VALIDATION_POLICY\)/);
    assert.match(validationSource, /export interface GuideRequestValidationPolicy/);
    assert.match(validationSource, /export function validateVisionGuideRequest/);
    assert.match(validationSource, /function validateGuidedSessionContext/);
    assert.match(validationSource, /function validatePendingPointOutcomeContext/);
    assert.match(validationSource, /function assertOptionalGuidedSessionText/);
    assert.match(validationSource, /MAX_SINGLE_SCREENSHOT_BASE64_CHARS/);
    assert.match(validationSource, /MAX_AD_MISSION_SNAPSHOT_CHARS/);
    assert.match(validationSource, /MAX_DEVICE_IDENTIFIER_CHARS/);
    assert.match(validationSource, /policy\.expectedOutcomes\.has/);
    assert.match(validationSource, /policy\.sensitiveEvidencePattern\.test/);
    assert.match(validationSource, /policy\.unsafePointLabelPattern\.test/);
    assert.match(contractSource, /import type \{ GuideRequestValidationPolicy \}/);
    assert.match(contractSource, /export const GUIDE_REQUEST_VALIDATION_POLICY: GuideRequestValidationPolicy/);
    assert.match(contractSource, /export const GUIDE_POINT_EXPECTED_OUTCOMES = new Set/);
    assert.match(contractSource, /export const GUIDE_SCREEN_STATES = new Set\(\["loading", "recognized", "unknown", "blocked"\]\)/);
    assert.match(contractSource, /export const POINT_RESTRICTED_SCREEN_IDS = new Set/);
    assert.match(contractSource, /export const POINT_RESTRICTED_STAGE_IDS = new Set/);
    assert.match(contractSource, /export const UNSAFE_POINT_LABEL_PATTERN =/);
    assert.match(contractSource, /export const SENSITIVE_GUIDE_EVIDENCE_PATTERN =/);
    assert.match(contractSource, /expectedOutcomes: GUIDE_POINT_EXPECTED_OUTCOMES/);
    assert.match(contractSource, /sensitiveEvidencePattern: SENSITIVE_GUIDE_EVIDENCE_PATTERN/);
    assert.match(contractSource, /unsafePointLabelPattern: UNSAFE_POINT_LABEL_PATTERN/);
    assert.doesNotMatch(indexSource, /from "\.\/guideRequestValidation"/);
    assert.doesNotMatch(indexSource, /from "\.\/guideResponseContract"/);
    assert.doesNotMatch(indexSource, /validateVisionGuideRequest\(body, GUIDE_REQUEST_VALIDATION_POLICY\)/);
    assert.doesNotMatch(indexSource, /function validateVisionGuideRequest\(/);
    assert.doesNotMatch(indexSource, /function validateGuidedSessionContext\(/);
    assert.doesNotMatch(indexSource, /function validatePendingPointOutcomeContext\(/);
    assert.doesNotMatch(indexSource, /function assertOptionalGuidedSessionText\(/);
    assert.doesNotMatch(indexSource, /MAX_SINGLE_SCREENSHOT_BASE64_CHARS/);
    assert.doesNotMatch(indexSource, /MAX_AD_MISSION_SNAPSHOT_CHARS/);
    assert.doesNotMatch(indexSource, /MAX_DEVICE_IDENTIFIER_CHARS/);
    assert.doesNotMatch(indexSource, /const GUIDE_REQUEST_VALIDATION_POLICY/);
    assert.doesNotMatch(indexSource, /const GUIDE_POINT_EXPECTED_OUTCOMES =/);
    assert.doesNotMatch(indexSource, /const GUIDE_SCREEN_STATES =/);
    assert.doesNotMatch(indexSource, /const POINT_RESTRICTED_SCREEN_IDS =/);
    assert.doesNotMatch(indexSource, /const POINT_RESTRICTED_STAGE_IDS =/);
    assert.doesNotMatch(indexSource, /const UNSAFE_POINT_LABEL_PATTERN =/);
    assert.doesNotMatch(indexSource, /const SENSITIVE_GUIDE_EVIDENCE_PATTERN =/);
  });

  test("worker OpenAI guide response parsing stays outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");
    const clientSource = readFileSync(path.join(workerRoot, "src", "openAIGuideClient.ts"), "utf8");
    const responseSource = readFileSync(path.join(workerRoot, "src", "openAIGuideResponse.ts"), "utf8");

    assert.match(visionGuideRoutesSource, /from "\.\/openAIGuideClient"/);
    assert.match(visionGuideRoutesSource, /requestOpenAIGuideOutputText\(\{/);
    assert.match(visionGuideRoutesSource, /apiKey: openAIAPIKey/);
    assert.match(visionGuideRoutesSource, /safetyIdentifier: user\.emailHash/);
    assert.match(clientSource, /export async function requestOpenAIGuideOutputText/);
    assert.match(clientSource, /fetch\("https:\/\/api\.openai\.com\/v1\/responses"/);
    assert.match(clientSource, /authorization: `Bearer \$\{input\.apiKey\}`/);
    assert.match(clientSource, /"OpenAI-Safety-Identifier": input\.safetyIdentifier/);
    assert.match(clientSource, /body: JSON\.stringify\(input\.payload\)/);
    assert.match(clientSource, /return await readOpenAIGuideOutputText\(response\)/);
    assert.match(responseSource, /export async function readOpenAIGuideOutputText/);
    assert.match(responseSource, /readBoundedResponseText\(/);
    assert.match(responseSource, /MAX_OPENAI_RESPONSE_BYTES/);
    assert.match(responseSource, /parseJSONText\(responseText, "OpenAI returned an invalid vision response\.", 502\)/);
    assert.match(responseSource, /function extractOpenAIOutputText/);
    assert.match(responseSource, /root\.output_text/);
    assert.match(responseSource, /content\.type === "output_text"/);
    assert.match(responseSource, /throw new HttpError\(502, "OpenAI returned no guide response\."\)/);
    assert.doesNotMatch(indexSource, /from "\.\/openAIGuideClient"/);
    assert.doesNotMatch(indexSource, /from "\.\/openAIGuideResponse"/);
    assert.doesNotMatch(indexSource, /requestOpenAIGuideOutputText\(\{/);
    assert.doesNotMatch(indexSource, /apiKey: openAIAPIKey/);
    assert.doesNotMatch(indexSource, /safetyIdentifier: user\.emailHash/);
    assert.doesNotMatch(indexSource, /readOpenAIGuideOutputText\(/);
    assert.doesNotMatch(indexSource, /function extractOutputText\(/);
    assert.doesNotMatch(indexSource, /function extractOpenAIOutputText\(/);
    assert.doesNotMatch(indexSource, /api\.openai\.com\/v1\/responses/);
    assert.doesNotMatch(indexSource, /authorization: `Bearer/);
    assert.doesNotMatch(indexSource, /"OpenAI-Safety-Identifier":/);
    assert.doesNotMatch(indexSource, /MAX_OPENAI_RESPONSE_BYTES/);
    assert.doesNotMatch(indexSource, /OpenAI returned an invalid vision response/);
    assert.doesNotMatch(indexSource, /OpenAI returned no guide response/);
    assert.doesNotMatch(indexSource, /OpenAI vision response is too large/);
  });

  test("worker OpenAI guide request and prompt stay outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");
    const requestSource = readFileSync(path.join(workerRoot, "src", "openAIGuideRequest.ts"), "utf8");
    const promptSource = readFileSync(path.join(workerRoot, "src", "visionGuidePrompt.ts"), "utf8");
    const promptContractsSource = readFileSync(
      path.join(workerRoot, "src", "visionGuidePromptContracts.ts"),
      "utf8"
    );
    const schemaSource = readFileSync(path.join(workerRoot, "src", "guideResponseSchema.ts"), "utf8");

    assert.match(visionGuideRoutesSource, /from "\.\/openAIGuideRequest"/);
    assert.match(visionGuideRoutesSource, /buildOpenAIGuideRequestPayload\(body, visionModel, user\.emailHash\)/);
    assert.match(requestSource, /export function buildOpenAIGuideRequestPayload/);
    assert.match(requestSource, /from "\.\/visionGuidePrompt"/);
    assert.match(requestSource, /from "\.\/guideResponseSchema"/);
    assert.match(requestSource, /detectPlatformPackForGuide/);
    assert.match(requestSource, /type: "input_image"/);
    assert.match(requestSource, /store: false/);
    assert.match(requestSource, /safety_identifier: safetyIdentifier/);
    assert.match(requestSource, /schema: spiderGuideSchema\(\)/);
    assert.match(promptSource, /export function buildVisionGuidePrompt/);
    assert.match(promptSource, /export function spiderMentorInstructions/);
    assert.match(promptSource, /from "\.\/visionGuidePromptContracts"/);
    assert.match(promptSource, /productFeaturePromptSummary/);
    assert.match(promptSource, /platformKnowledgeSummaryForPrompt/);
    assert.match(promptSource, /metaAdsBestPracticesForPrompt/);
    assert.match(promptContractsSource, /export function semanticScreenUnderstandingContractForPrompt/);
    assert.match(promptContractsSource, /export function screenGuidanceDecisionPipelineForPrompt/);
    assert.match(promptContractsSource, /export function guideDecisionContractForPrompt/);
    assert.match(promptContractsSource, /productFeatureContractForPrompt/);
    assert.match(promptContractsSource, /GUIDE_SCREEN_STATES/);
    assert.match(promptContractsSource, /POINT_RESTRICTED_STAGE_IDS/);
    assert.match(schemaSource, /export function spiderGuideSchema/);
    assert.doesNotMatch(indexSource, /from "\.\/openAIGuideRequest"/);
    assert.doesNotMatch(indexSource, /buildOpenAIGuideRequestPayload\(body, visionModel, user\.emailHash\)/);
    assert.doesNotMatch(indexSource, /function buildVisionRequest\(/);
    assert.doesNotMatch(indexSource, /function buildVisionPrompt\(/);
    assert.doesNotMatch(indexSource, /function spiderMentorInstructions\(/);
    assert.doesNotMatch(indexSource, /spiderGuideSchema\(\)/);
    assert.doesNotMatch(indexSource, /productFeaturePromptSummary/);
    assert.doesNotMatch(indexSource, /platformContextForPrompt/);
    assert.doesNotMatch(indexSource, /metaAdsBestPracticesForPrompt/);
    assert.doesNotMatch(indexSource, /GUIDE_SCREEN_STATES/);
    assert.doesNotMatch(promptSource, /function semanticScreenUnderstandingContractForPrompt\(/);
    assert.doesNotMatch(promptSource, /function guideDecisionContractForPrompt\(/);
  });

  test("worker guide response validation stays outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const visionGuideRoutesSource = readFileSync(path.join(workerRoot, "src", "visionGuideRoutes.ts"), "utf8");
    const validationSource = readFileSync(path.join(workerRoot, "src", "guideResponseValidation.ts"), "utf8");
    const validationContextSource = readFileSync(path.join(workerRoot, "src", "guideValidationContext.ts"), "utf8");
    const groundingSource = readFileSync(path.join(workerRoot, "src", "guideSemanticGrounding.ts"), "utf8");
    const pointParsingSource = readFileSync(path.join(workerRoot, "src", "guidePointParsing.ts"), "utf8");
    const screenSafetySource = readFileSync(path.join(workerRoot, "src", "guideScreenSafety.ts"), "utf8");
    const pointSafetySource = readFileSync(path.join(workerRoot, "src", "guidePointSafety.ts"), "utf8");
    const parsingSource = readFileSync(path.join(workerRoot, "src", "guideResponseParsing.ts"), "utf8");
    const extrasSource = readFileSync(path.join(workerRoot, "src", "guideResponseExtras.ts"), "utf8");
    const contractSource = readFileSync(path.join(workerRoot, "src", "guideResponseContract.ts"), "utf8");

    assert.match(visionGuideRoutesSource, /from "\.\/guideResponseValidation"/);
    assert.match(visionGuideRoutesSource, /from "\.\/guideValidationContext"/);
    assert.match(visionGuideRoutesSource, /guideResponsePayload\(outputText, guideValidationContextForRequest\(body\)\)/);
    assert.match(validationContextSource, /export interface GuideValidationContext/);
    assert.match(validationContextSource, /export function guideValidationContextForRequest/);
    assert.match(validationContextSource, /function guidePendingPointOutcomeOrNull/);
    assert.match(validationContextSource, /GUIDE_POINT_EXPECTED_OUTCOMES/);
    assert.match(validationSource, /from "\.\/guideSemanticGrounding"/);
    assert.match(validationSource, /from "\.\/guidePointParsing"/);
    assert.match(validationSource, /from "\.\/guideScreenSafety"/);
    assert.match(validationSource, /from "\.\/guideResponseParsing"/);
    assert.match(validationSource, /from "\.\/guideResponseExtras"/);
    assert.match(validationSource, /from "\.\/guideValidationContext"/);
    assert.match(validationSource, /export function guideResponsePayload/);
    assert.doesNotMatch(validationSource, /export interface GuideValidationContext/);
    assert.doesNotMatch(validationSource, /export function guideValidationContextForRequest/);
    assert.doesNotMatch(validationSource, /function guidePendingPointOutcomeOrNull/);
    assert.match(validationSource, /SENSITIVE_GUIDE_EVIDENCE_PATTERN/);
    assert.match(pointParsingSource, /export function guidePointOrNull/);
    assert.match(pointParsingSource, /MAX_GUIDE_POINT_LABEL_CHARS/);
    assert.match(pointParsingSource, /MAX_SCREENSHOT_DIMENSION_PIXELS/);
    assert.match(pointParsingSource, /GUIDE_POINT_EXPECTED_OUTCOMES/);
    assert.match(pointParsingSource, /SENSITIVE_GUIDE_EVIDENCE_PATTERN/);
    assert.match(screenSafetySource, /from "\.\/guidePointSafety"/);
    assert.match(screenSafetySource, /export interface GuideScreenSafetyInput/);
    assert.match(screenSafetySource, /export function assertGuideScreenSafety/);
    assert.match(screenSafetySource, /function guideScreenOrStageRestrictsPoint/);
    assert.match(screenSafetySource, /GUIDE_LOADING_SCREEN_ID/);
    assert.match(screenSafetySource, /GUIDE_UNKNOWN_SCREEN_ID/);
    assert.match(screenSafetySource, /POINT_RESTRICTED_SCREEN_IDS/);
    assert.match(groundingSource, /export function guideSemanticGrounding/);
    assert.match(groundingSource, /export function withDerivedSemanticSignature/);
    assert.match(groundingSource, /function semanticSignatureForGrounding/);
    assert.match(groundingSource, /function guideSceneGraphElementArray/);
    assert.match(groundingSource, /function guideGroundingTargetArray/);
    assert.match(groundingSource, /MAX_GUIDE_GROUNDING_TARGETS \* 3/);
    assert.match(groundingSource, /GUIDE_GROUNDING_TARGET_ROLES/);
    assert.match(groundingSource, /SENSITIVE_GUIDE_EVIDENCE_PATTERN/);
    assert.match(pointSafetySource, /export interface GuidePointValidationContext/);
    assert.match(pointSafetySource, /export function assertGuidePointIsSafe/);
    assert.match(pointSafetySource, /export function assertGuidePointIsGrounded/);
    assert.match(pointSafetySource, /function guideTargetCanOwnPoint/);
    assert.match(pointSafetySource, /function guideActionRiskForTarget/);
    assert.match(pointSafetySource, /function guideTargetElementIsValid/);
    assert.match(pointSafetySource, /function isPlausibleGuideTargetRegion/);
    assert.match(pointSafetySource, /function targetEvidenceAllowsOutsideModalContext/);
    assert.match(pointSafetySource, /GUIDE_DOT_ACTION_RISKS/);
    assert.match(pointSafetySource, /GUIDE_POINT_AFFORDANCES/);
    assert.match(pointSafetySource, /GUIDE_STALE_TARGET_STABILITIES/);
    assert.match(pointSafetySource, /SENSITIVE_GUIDE_EVIDENCE_PATTERN/);
    assert.match(pointSafetySource, /UNSAFE_POINT_LABEL_PATTERN/);
    assert.match(parsingSource, /export function invalidGuideResponse/);
    assert.match(parsingSource, /export function boundedGuideString/);
    assert.match(parsingSource, /export function optionalBoundedGuideString/);
    assert.match(parsingSource, /export function normalizedGuideText/);
    assert.match(extrasSource, /export function guideArtifactOrNull/);
    assert.match(extrasSource, /export function guideAdMissionUpdateOrNull/);
    assert.match(extrasSource, /function optionalBoundedGuideStringArray/);
    assert.match(extrasSource, /GUIDE_ARTIFACT_KINDS/);
    assert.match(extrasSource, /MAX_AD_MISSION_TEXT_FIELD_CHARS/);
    assert.match(contractSource, /export const GUIDE_SCREEN_STATES = new Set\(\["loading", "recognized", "unknown", "blocked"\]\)/);
    assert.match(contractSource, /export const GUIDE_DOT_ACTION_RISKS = new Set\(\["reversible", "navigation", "selection", "input"\]\)/);
    assert.match(contractSource, /export const POINT_RESTRICTED_SCREEN_IDS = new Set/);
    assert.match(contractSource, /export const POINT_RESTRICTED_STAGE_IDS = new Set/);
    assert.match(contractSource, /export const SENSITIVE_GUIDE_EVIDENCE_PATTERN =/);
    assert.match(contractSource, /export const UNSAFE_POINT_LABEL_PATTERN =/);
    assert.doesNotMatch(indexSource, /from "\.\/guideResponseValidation"/);
    assert.doesNotMatch(indexSource, /guideResponsePayload\(outputText, guideValidationContextForRequest\(body\)\)/);
    assert.doesNotMatch(indexSource, /function guideResponsePayload\(/);
    assert.doesNotMatch(indexSource, /interface GuideValidationContext/);
    assert.doesNotMatch(indexSource, /function guidePendingPointOutcomeOrNull\(/);
    assert.doesNotMatch(indexSource, /function assertGuideScreenSafety\(/);
    assert.doesNotMatch(indexSource, /function assertGuidePointIsSafe\(/);
    assert.doesNotMatch(indexSource, /function assertGuidePointIsGrounded\(/);
    assert.doesNotMatch(indexSource, /function guideTargetCanOwnPoint\(/);
    assert.doesNotMatch(indexSource, /function guideActionRiskForTarget\(/);
    assert.doesNotMatch(indexSource, /function semanticSignatureForGrounding\(/);
    assert.doesNotMatch(indexSource, /function guidePointOrNull\(/);
    assert.doesNotMatch(indexSource, /function invalidGuideResponse\(/);
    assert.doesNotMatch(validationSource, /function semanticSignatureForGrounding\(/);
    assert.doesNotMatch(validationSource, /function guideSemanticGrounding\(/);
    assert.doesNotMatch(validationSource, /function guideSceneGraphElementArray\(/);
    assert.doesNotMatch(validationSource, /function guideGroundingTargetArray\(/);
    assert.doesNotMatch(validationSource, /function guidePointOrNull\(/);
    assert.doesNotMatch(validationSource, /function assertGuideScreenSafety\(/);
    assert.doesNotMatch(validationSource, /function assertGuidePointIsSafe\(/);
    assert.doesNotMatch(validationSource, /function assertGuidePointIsGrounded\(/);
    assert.doesNotMatch(validationSource, /function guideTargetCanOwnPoint\(/);
    assert.doesNotMatch(validationSource, /function guideActionRiskForTarget\(/);
    assert.doesNotMatch(validationSource, /function invalidGuideResponse\(/);
    assert.doesNotMatch(validationSource, /function guideArtifactOrNull\(/);
    assert.doesNotMatch(validationSource, /function guideAdMissionUpdateOrNull\(/);
    assert.doesNotMatch(validationSource, /function optionalBoundedGuideStringArray\(/);
    assert.doesNotMatch(pointSafetySource, /from "\.\/guideResponseValidation"/);
  });

  test("worker guide response schema stays outside the route monolith", () => {
    const indexSource = readFileSync(path.join(workerRoot, "src", "index.ts"), "utf8");
    const requestSource = readFileSync(path.join(workerRoot, "src", "openAIGuideRequest.ts"), "utf8");
    const schemaSource = readFileSync(path.join(workerRoot, "src", "guideResponseSchema.ts"), "utf8");
    const contractSource = readFileSync(path.join(workerRoot, "src", "guideResponseContract.ts"), "utf8");

    assert.match(requestSource, /from "\.\/guideResponseSchema"/);
    assert.match(requestSource, /schema: spiderGuideSchema\(\)/);
    assert.match(schemaSource, /export function spiderGuideSchema/);
    assert.match(schemaSource, /function semanticGroundingSchema/);
    assert.match(schemaSource, /from "\.\/guideLimits"/);
    assert.match(schemaSource, /from "\.\/guideResponseContract"/);
    assert.match(schemaSource, /MAX_GUIDE_GROUNDING_TARGETS \* 3/);
    assert.match(schemaSource, /MAX_GUIDE_SCREEN_EVIDENCE_ITEMS/);
    assert.match(schemaSource, /GUIDE_SCREEN_STATES/);
    assert.match(schemaSource, /GUIDE_CONTEXT_KINDS/);
    assert.match(schemaSource, /GUIDE_DECISIONS/);
    assert.match(schemaSource, /GUIDE_POINT_EXPECTED_OUTCOMES/);
    assert.match(schemaSource, /GUIDE_ARTIFACT_KINDS/);
    assert.match(schemaSource, /GUIDE_GROUNDING_TARGET_ROLES/);
    assert.match(schemaSource, /GUIDE_GROUNDING_TARGET_AFFORDANCES/);
    assert.match(schemaSource, /GUIDE_GROUNDING_TARGET_STABILITIES/);
    assert.match(schemaSource, /GUIDE_SCENE_GRAPH_Z_INDEX_HINTS/);
    assert.match(contractSource, /export const GUIDE_ARTIFACT_KINDS = new Set/);
    assert.match(contractSource, /export const GUIDE_SCREEN_STATES = new Set\(\["loading", "recognized", "unknown", "blocked"\]\)/);
    assert.doesNotMatch(indexSource, /from "\.\/guideResponseSchema"/);
    assert.doesNotMatch(indexSource, /schema: spiderGuideSchema\(\)/);
    assert.doesNotMatch(indexSource, /function spiderGuideSchema\(/);
    assert.doesNotMatch(indexSource, /function semanticGroundingSchema\(/);
    assert.doesNotMatch(indexSource, /MAX_GUIDE_GROUNDING_TARGETS \* 3/);
    assert.doesNotMatch(indexSource, /MAX_GUIDE_SCREEN_EVIDENCE_ITEMS/);
  });
}
