#!/usr/bin/env bash
# Create an isolated git worktree for parallel Clicky development.
#
# Usage:
#   ./scripts/new-worktree.sh <branch-name> [--primary] [--path <directory>]
#
# Examples:
#   ./scripts/new-worktree.sh feature/memory-routines
#   ./scripts/new-worktree.sh memory-routines --primary
#   ./scripts/new-worktree.sh feature/skills-v2 --path ../clicky-skills-v2
#
# Each worktree gets its own data home, UserDefaults suite, and (by default)
# disables the global push-to-talk hotkey so multiple instances do not conflict.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_BRANCH="${CLICKY_WORKTREE_BASE:-origin/feature/teaching-skills-upstream}"

usage() {
  sed -n '3,12p' "$0"
  exit 1
}

BRANCH_NAME=""
WORKTREE_PATH=""
IS_PRIMARY="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --primary)
      IS_PRIMARY="1"
      shift
      ;;
    --path)
      WORKTREE_PATH="${2:-}"
      [[ -n "$WORKTREE_PATH" ]] || usage
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      if [[ -z "$BRANCH_NAME" ]]; then
        BRANCH_NAME="$1"
        shift
      else
        echo "Unknown argument: $1" >&2
        usage
      fi
      ;;
  esac
done

[[ -n "$BRANCH_NAME" ]] || usage

if [[ "$BRANCH_NAME" != */* ]]; then
  BRANCH_NAME="feature/$BRANCH_NAME"
fi

slug="${BRANCH_NAME#feature/}"
slug="${slug//\//-}"
slug="$(echo "$slug" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')"

CLICKY_HOME="/tmp/clicky-${slug}"
CLICKY_DEFAULTS_SUITE="clicky-${slug}"

if [[ -z "$WORKTREE_PATH" ]]; then
  WORKTREE_PATH="$(dirname "$ROOT_DIR")/clicky-${slug}"
fi

if [[ ! "$WORKTREE_PATH" = /* ]]; then
  WORKTREE_PATH="$(cd "$ROOT_DIR" && cd "$(dirname "$WORKTREE_PATH")" && pwd)/$(basename "$WORKTREE_PATH")"
fi

echo "Fetching latest $BASE_BRANCH..."
git -C "$ROOT_DIR" fetch origin --prune

if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
  echo "Branch already exists locally: $BRANCH_NAME"
  git -C "$ROOT_DIR" worktree add "$WORKTREE_PATH" "$BRANCH_NAME"
else
  git -C "$ROOT_DIR" worktree add -b "$BRANCH_NAME" "$WORKTREE_PATH" "$BASE_BRANCH"
fi

mkdir -p "$CLICKY_HOME/skills"

cat >"$WORKTREE_PATH/.clicky-worktree.env" <<EOF
# Generated by scripts/new-worktree.sh — do not commit.
CLICKY_BRANCH=$BRANCH_NAME
CLICKY_HOME=$CLICKY_HOME
CLICKY_DEFAULTS_SUITE=$CLICKY_DEFAULTS_SUITE
CLICKY_DISABLE_GLOBAL_PTT=$([[ "$IS_PRIMARY" == "1" ]] && echo "0" || echo "1")
EOF

SCHEME_PATH="$WORKTREE_PATH/leanring-buddy.xcodeproj/xcshareddata/xcschemes/leanring-buddy.xcscheme"
DISABLE_PTT="$([[ "$IS_PRIMARY" == "1" ]] && echo "0" || echo "1")"

python3 - "$SCHEME_PATH" "$CLICKY_HOME" "$CLICKY_DEFAULTS_SUITE" "$DISABLE_PTT" <<'PY'
import sys
import xml.etree.ElementTree as ET

scheme_path, clicky_home, defaults_suite, disable_ptt = sys.argv[1:5]

tree = ET.parse(scheme_path)
root = tree.getroot()
launch_action = root.find("LaunchAction")
if launch_action is None:
    raise SystemExit("LaunchAction not found in scheme")

for tag in ("EnvironmentVariables", "CommandLineArguments"):
    existing = launch_action.find(tag)
    if existing is not None:
        launch_action.remove(existing)

environment_variables = ET.SubElement(launch_action, "EnvironmentVariables")
ET.SubElement(
    environment_variables,
    "EnvironmentVariable",
    {
        "key": "CLICKY_HOME",
        "value": clicky_home,
        "isEnabled": "YES",
    },
)

command_line_arguments = ET.SubElement(launch_action, "CommandLineArguments")
ET.SubElement(
    command_line_arguments,
    "CommandLineArgument",
    {
        "argument": f"-CLICKY_DEFAULTS_SUITE={defaults_suite}",
        "isEnabled": "YES",
    },
)

if disable_ptt == "1":
    ET.SubElement(
        command_line_arguments,
        "CommandLineArgument",
        {
            "argument": "-CLICKY_DISABLE_GLOBAL_PTT=1",
            "isEnabled": "YES",
        },
    )

tree.write(scheme_path, encoding="UTF-8", xml_declaration=True)
PY

chmod +x "$WORKTREE_PATH/scripts/new-worktree.sh" 2>/dev/null || true

cat <<EOF

Worktree ready.

  Path:              $WORKTREE_PATH
  Branch:            $BRANCH_NAME
  Data home:         $CLICKY_HOME
  UserDefaults:      $CLICKY_DEFAULTS_SUITE
  Global PTT:        $([[ "$IS_PRIMARY" == "1" ]] && echo "enabled (primary)" || echo "disabled")

Next:
  1. open "$WORKTREE_PATH/leanring-buddy.xcodeproj"
  2. Run from Xcode (scheme args are already set in this worktree only)
  3. Grant TCC permissions to THIS build if macOS asks

Tip: mark only one worktree as --primary so Control+Option push-to-talk stays on your main dev copy.

EOF
