"""initial schema

Revision ID: 973820dae025
Revises: 
Create Date: 2026-04-11 13:29:14.644812
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '973820dae025'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('authentication_subject_identifier', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_image_url', sa.String(length=2048), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentication_subject_identifier'), 'users', ['authentication_subject_identifier'], unique=True)
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_session_token_hash'), 'auth_sessions', ['session_token_hash'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('launch_state', sa.Enum('stopped', 'running', name='workspace_launch_state'), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_workspace_created_at', 'agents', ['workspace_id', 'created_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('root_entry_path', sa.String(length=4096), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('course_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'root_entry_path', name='uq_courses_workspace_root_entry_path')
    )
    op.create_index('ix_courses_workspace_updated_at', 'courses', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('workspace_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('entry_name', sa.String(length=255), nullable=False),
    sa.Column('entry_path', sa.String(length=4096), nullable=False),
    sa.Column('entry_type', sa.Enum('directory', 'file', name='workspace_entry_type'), nullable=False),
    sa.Column('content_type', sa.Enum('markdown', 'pdf', 'image', 'text', 'other', name='workspace_content_type'), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('binary_content', sa.LargeBinary(), nullable=True),
    sa.Column('storage_object_key', sa.String(length=2048), nullable=True),
    sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_entry_id'], ['workspace_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entry_path', name='uq_workspace_entries_workspace_path')
    )
    op.create_index('ix_workspace_entries_workspace_parent', 'workspace_entries', ['workspace_id', 'parent_entry_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='workspace_membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_memberships_workspace_user')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_workspace_updated_at', 'agent_sessions', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('learner_topic_masteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('topic_title', sa.String(length=255), nullable=True),
    sa.Column('mastery_score', sa.BigInteger(), nullable=False),
    sa.Column('confidence_score', sa.BigInteger(), nullable=False),
    sa.Column('strength_notes', sa.Text(), nullable=True),
    sa.Column('gap_notes', sa.Text(), nullable=True),
    sa.Column('explanation_strategy', sa.Text(), nullable=True),
    sa.Column('prerequisite_topic_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('times_assessed', sa.BigInteger(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastery_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'topic_key', name='uq_learner_topic_masteries_course_topic_key')
    )
    op.create_index('ix_learner_topic_masteries_course_updated_at', 'learner_topic_masteries', ['course_id', 'updated_at'], unique=False)
    op.create_index('ix_learner_topic_masteries_workspace_course', 'learner_topic_masteries', ['workspace_id', 'course_id'], unique=False)
    op.create_table('workspace_ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_entry_id', sa.UUID(), nullable=False),
    sa.Column('source_entry_path', sa.String(length=4096), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='workspace_ingestion_job_status'), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('output_bundle_path', sa.String(length=4096), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['workspace_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_ingestion_jobs_workspace_created_at', 'workspace_ingestion_jobs', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_workspace_ingestion_jobs_workspace_source_path', 'workspace_ingestion_jobs', ['workspace_id', 'source_entry_path'], unique=False)
    op.create_table('agent_session_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_session_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('sequence_index', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('provider_response_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_session_id', 'sequence_index', name='uq_agent_session_messages_sequence')
    )
    op.create_index('ix_agent_session_messages_run_id', 'agent_session_messages', ['run_id'], unique=False)
    op.create_index('ix_agent_session_messages_session_sequence', 'agent_session_messages', ['agent_session_id', 'sequence_index'], unique=False)
    op.create_index('ix_agent_session_messages_workspace_created_at', 'agent_session_messages', ['workspace_id', 'created_at'], unique=False)
    op.create_table('learner_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('topic_mastery_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('agent_session_message_id', sa.UUID(), nullable=True),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.Column('assessed_mastery_score', sa.BigInteger(), nullable=True),
    sa.Column('assessed_confidence_score', sa.BigInteger(), nullable=True),
    sa.Column('observation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_session_message_id'], ['agent_session_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_mastery_id'], ['learner_topic_masteries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learner_observations_course_created_at', 'learner_observations', ['course_id', 'created_at'], unique=False)
    op.create_index('ix_learner_observations_workspace_created_at', 'learner_observations', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learner_observations_workspace_created_at', table_name='learner_observations')
    op.drop_index('ix_learner_observations_course_created_at', table_name='learner_observations')
    op.drop_table('learner_observations')
    op.drop_index('ix_agent_session_messages_workspace_created_at', table_name='agent_session_messages')
    op.drop_index('ix_agent_session_messages_session_sequence', table_name='agent_session_messages')
    op.drop_index('ix_agent_session_messages_run_id', table_name='agent_session_messages')
    op.drop_table('agent_session_messages')
    op.drop_index('ix_workspace_ingestion_jobs_workspace_source_path', table_name='workspace_ingestion_jobs')
    op.drop_index('ix_workspace_ingestion_jobs_workspace_created_at', table_name='workspace_ingestion_jobs')
    op.drop_table('workspace_ingestion_jobs')
    op.drop_index('ix_learner_topic_masteries_workspace_course', table_name='learner_topic_masteries')
    op.drop_index('ix_learner_topic_masteries_course_updated_at', table_name='learner_topic_masteries')
    op.drop_table('learner_topic_masteries')
    op.drop_index('ix_agent_sessions_workspace_updated_at', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('workspace_memberships')
    op.drop_index('ix_workspace_entries_workspace_parent', table_name='workspace_entries')
    op.drop_table('workspace_entries')
    op.drop_index('ix_courses_workspace_updated_at', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_agents_workspace_created_at', table_name='agents')
    op.drop_table('agents')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_auth_sessions_session_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.drop_index(op.f('ix_users_authentication_subject_identifier'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
